### ISSUE TITLE
Fix docker-based CI failures

### ISSUE THREAD

**Issue by filler** [rackerlabs/cookbook-repose#57]
Currently Travis ralphs testing the containers in Docker.  At first glance this appears to be a result of `start-stop-daemon` expectations vs `docker` constraints.  Someone needs to roll up sleeves, jump in, and identify the issue.

Alternatively, container-based CI could be scrapped in-favor of ... whatever else FOSS Travis allows for.

**Comment by drenalin23** [comment]
This is fixed for now.
