### ISSUE TITLE
README vs code

### ISSUE THREAD

**Issue by shawnashlee** [rackerlabs/cookbook-repose#79]
Lines 253 and 254 in the README show `uri-regex` and `http-methods` under the example for `node['repose']['rate_limiting']['limit_groups']`, while the [template code](https://github.com/rackerlabs/cookbook-repose/blob/master/templates/default/rate-limiting.cfg.xml.erb#L31) actually uses `uri_regex` and `http_methods`. I was going to just put in a PR but noticed the example on line 273 of the README for the global limits example that it also uses `uri-regex` but is correctly used in [the template](https://github.com/rackerlabs/cookbook-repose/blob/master/templates/default/rate-limiting.cfg.xml.erb#L21). So, my question is, would you rather simply have the README updated or unify how those similar attributes are called?

**Comment by filler** [comment]
It would likely be better to true up the `README` as that would be inherently less breaking for those who maintain wrappers, overrides.  Or am I missing something obvious and need to :coffee: more? :trollface:

**Comment by drenalin23** [comment]
https://github.com/rackerlabs/cookbook-repose/pull/80
